export const GET_CRYSTAL_PROFILE =
    "OktanAGC/App/GET_CRYSTAL_PROFILE";
export const SET_CRYSTAL_PROFILE =
    "OktanAGC/App/SET_CRYSTAL_PROFILE";
export const EDIT_CRYSTAL_PROFILE =
    "OktanAGC/App/EDIT_CRYSTAL_PROFILE";
export const SUCCESS_EDIT_CRYSTAL_PROFILE =
    "OktanAGC/App/SUCCESS_EDIT_CRYSTAL_PROFILE";