export const GET_QUESTIONS_DATA =
    "OktanAGC/App/GET_QUESTIONS_DATA";
export const SET_QUESTIONS_DATA =
    "OktanAGC/App/SET_QUESTIONS_DATA";
export const EDIT_QUESTION_DATA =
    "OktanAGC/App/EDIT_QUESTION_DATA";
export const SUCCESS_EDIT_QUESTION_DATA =
    "OktanAGC/App/SUCCESS_EDIT_QUESTION_DATA";
export const DELETE_QUESTION_DATA =
    "OktanAGC/App/DELETE_QUESTION_DATA";
export const SUCCESS_DELETE_QUESTION_DATA =
    "OktanAGC/App/SUCCESS_DELETE_QUESTION_DATA";
export const CREATE_QUESTION =
    "OktanAGC/App/CREATE_QUESTION";
export const SUCCESS_CREATE_QUESTION =
    "OktanAGC/App/SUCCESS_CREATE_QUESTION";
export const GET_QUESTION_DETAIL =
    "OktanAGC/App/GET_QUESTION_DETAIL";
export const SET_QUESTION_DETAIL =
    "OktanAGC/App/SET_QUESTION_DETAIL";