export const GET_ISOTERM_PROFILE =
    "OktanAGC/App/GET_ISOTERM_PROFILE";
export const SET_ISOTERM_PROFILE =
    "OktanAGC/App/SET_ISOTERM_PROFILE";
export const EDIT_ISOTERM_PROFILE =
    "OktanAGC/App/EDIT_ISOTERM_PROFILE";
export const SUCCESS_EDIT_ISOTERM_PROFILE =
    "OktanAGC/App/SUCCESS_EDIT_ISOTERM_PROFILE";