export const GET_CONTESTANTS_DATA =
    "OktanAGC/App/GET_CONTESTANTS_DATA";
export const SET_CONTESTANTS_DATA =
    "OktanAGC/App/SET_CONTESTANTS_DATA";
export const VERIFY_CONTESTANT_DATA =
    "OktanAGC/App/VERIFY_CONTESTANT_DATA";
export const SUCCESS_VERIFY_CONTESTANT_DATA =
    "OktanAGC/App/SUCCESS_VERIFY_CONTESTANT_DATA";
export const DELETE_CONTESTANT_DATA =
    "OktanAGC/App/DELETE_CONTESTANT_DATA";
export const SUCCESS_DELETE_CONTESTANT_DATA =
    "OktanAGC/App/SUCCESS_DELETE_CONTESTANT_DATA";
export const DOWNLOAD_CONTESTANT_DATA =
    "OktanAGC/App/DOWNLOAD_CONTESTANT_DATA";
export const SUCCESS_DOWNLOAD_CONTESTANT_DATA =
    "OktanAGC/App/SUCCESS_DOWNLOAD_CONTESTANT_DATA";